use pinned versions

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -4,7 +4,7 @@
 
 # This workflow will build the project and run some basic tests.
 
-name: Continuous Integration
+name: Continuous Integration (ANT)
 
 on:
   workflow_dispatch:
@@ -13,8 +13,11 @@ on:
   pull_request:
     branches: [ "main" ]
 
+# Declare default permissions as read only.
+permissions: read-all
+
 jobs:
-  Build:
+  build:
     permissions:
       contents: write
       packages: write
@@ -33,74 +36,74 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout
-      uses: actions/checkout@v3
+      - name: Checkout
+        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
 
-    - name: Set Project Name
-      run: |
-        echo MY_PROJECTNAME=$(pwd | xargs basename) >> $GITHUB_ENV
-        echo "# Project $(pwd | xargs basename)" >> $GITHUB_STEP_SUMMARY
+      - name: Set Project Name
+        run: |
+          echo MY_PROJECTNAME=$(pwd | xargs basename) >> $GITHUB_ENV
+          echo "# Project $(pwd | xargs basename)" >> $GITHUB_STEP_SUMMARY
 
-    - name: Check REUSE compliance
-      run: |
-        pip install reuse
-        echo "## REUSE Compliance" >> $GITHUB_STEP_SUMMARY
-        echo "For more information about REUSE see [official page](https://reuse.software/)."
-        reuse lint | sed  s'/# /### /g' >> $GITHUB_STEP_SUMMARY
+      - name: Check REUSE compliance
+        run: |
+          pip install reuse
+          echo "## REUSE Compliance" >> $GITHUB_STEP_SUMMARY
+          echo "For more information about REUSE see [official page](https://reuse.software/)."
+          reuse lint | sed  s'/# /### /g' >> $GITHUB_STEP_SUMMARY
 
-    - name: Set Up JDK 11
-      uses: actions/setup-java@v3
-      with:
-        java-version: '11'
-        distribution: 'temurin'
+      - name: Set Up JDK 11
+        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
+        with:
+          java-version: '11'
+          distribution: 'temurin'
   
-    - name: Prepare Build environment
-      run: |
-        sudo apt-get install nsis
-        ant -noinput -buildfile build.xml prepare-environment
+      - name: Prepare Build environment
+        run: |
+          sudo apt-get install nsis
+          ant -noinput -buildfile build.xml prepare-environment
 
-    - name: Build With Ant
-      run: xvfb-run ant -noinput -lib target/build-environment/ant-libraries -buildfile build.xml
+      - name: Build With Ant
+        run: xvfb-run ant -noinput -lib target/build-environment/ant-libraries -buildfile build.xml
 
-    - name: Add Headline Job Summary
-      run: echo "## JUnit " >> $GITHUB_STEP_SUMMARY
+      - name: Add Headline Job Summary
+        run: echo "## JUnit " >> $GITHUB_STEP_SUMMARY
       
-    - name: Publish Test Report
-      uses: mikepenz/action-junit-report@v3.7.4
-      if: success() || failure() # always run even if the previous step fails
-      with:
-        report_paths: target/build/reports/junit-report/TEST-*.xml
-        detailed_summary: true
-        include_passed: true
-        fail_on_failure: true
-        require_tests: true
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@75b84e78b3f0aaea7ed7cf8d1d100d7f97f963ec # v4.0.0
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: target/build/reports/junit-report/TEST-*.xml
+          detailed_summary: true
+          include_passed: true
+          fail_on_failure: true
+          require_tests: true
 
-    - name: JaCoCo Code Coverage Report
-      id: jacoco_reporter
-      uses: PavanMudigonda/jacoco-reporter@v4.8
-      with:
-        coverage_results_path: target/build/reports/jacoco-report/jacoco.xml
-        coverage_report_name: Coverage
-        coverage_report_title: ${{ env.MY_PROJECTNAME }}
-        github_token: ${{ secrets.GITHUB_TOKEN }}
-        skip_check_run: false
-        minimum_coverage: 80
-        fail_below_threshold: false
-        publish_only_summary: false
+      - name: JaCoCo Code Coverage Report
+        id: jacoco_reporter
+        uses: PavanMudigonda/jacoco-reporter@ffe0b95c14292be4d076e56d50ba6c3b94c43a77 # v4.8
+        with:
+          coverage_results_path: target/build/reports/jacoco-report/jacoco.xml
+          coverage_report_name: Coverage
+          coverage_report_title: ${{ env.MY_PROJECTNAME }}
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          skip_check_run: false
+          minimum_coverage: 80
+          fail_below_threshold: false
+          publish_only_summary: false
         
-    - name: Add Coverage Job Summary
-      run: echo "## Code Coverage ${{ env.coveragePercentageString }}" >> $GITHUB_STEP_SUMMARY
+      - name: Add Coverage Job Summary
+        run: echo "## Code Coverage ${{ env.coveragePercentageString }}" >> $GITHUB_STEP_SUMMARY
       
-    - name: Upload Package
-      uses: actions/upload-artifact@v3
-      with:
-        name: auto-mouse_package
-        path: target/distribution/auto-mouse.tar.gz
-        if-no-files-found: error
+      - name: Upload Package
+        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
+        with:
+          name: auto-mouse_package
+          path: target/distribution/auto-mouse.tar.gz
+          if-no-files-found: error
 
-    - name: Upload RPM
-      uses: actions/upload-artifact@v3
-      with:
-        name: auto-mouse_rpm
-        path: target/distribution/*.rpm
-        if-no-files-found: error
+      - name: Upload RPM
+        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
+        with:
+          name: auto-mouse_rpm
+          path: target/distribution/*.rpm
+          if-no-files-found: error
